package com.drools.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private String message;
    private String originalWord;

	public Message(String message) {
		this.message = message;
	}

	public String getMessage() {
		return message;
	}

	public String getOriginalWord() {
		return originalWord;
	}

	public void setOriginalWord(String originalWord) {
		this.originalWord = originalWord;
	}

	@Override
	public String toString() {
		return "Message{" +
				"message='" + message + '\'' +
				", originalWord='" + originalWord + '\'' +
				'}';
	}




}